// first column unmodified, second with control

{" ",		"\x80"		},		// KeySpace
{ "\x1b",	"\x1b"		},         	// KeyEscape
{ "\x7f",	"\x7f"		},         	// KeyBackspace
{ "\t",		"\t"		},           	// KeyTabulator
{ "\n",		"\n"		},           	// KeyReturn
{ "\x1b[2~",	"\x1b[2~"	},      	// KeyInsert
{ "\x1b[1~",	"\x1b[1~"	},      	// KeyHome
{ "\x1b[5~",	"\x1b[5~"	},      	// KeyPageUp
{ "\x1b[3~",	"\x1b[3~"	},      	// KeyDelete
{ "\x1b[4~",	"\x1b[4~"	},      	// KeyEnd
{ "\x1b[6~",	"\x1b[6~"	},      	// KeyPageDown
{ "\x1b[A",	"\x1b[5A"	},       	// KeyUp
{ "\x1b[B",	"\x1b[5B"	},       	// KeyDown
{ "\x1b[D",	"\x1b[5D"	},       	// KeyLeft
{ "\x1b[C",	"\x1b[5C"	},       	// KeyRight
{ "\x1b[[A",	"\x1b[[A"	},      	// KeyF1
{ "\x1b[[B",	"\x1b[[B"	},      	// KeyF2
{ "\x1b[[C",	"\x1b[[C"	},      	// KeyF3
{ "\x1b[[D",	"\x1b[[D"	},      	// KeyF4
{ "\x1b[[E",	"\x1b[[E"	},      	// KeyF5
{ "\x1b[17~",	"\x1b[17~"	},     		// KeyF6
{ "\x1b[18~",	"\x1b[18~"	},     		// KeyF7
{ "\x1b[19~",	"\x1b[19~"	},     		// KeyF8
{ "\x1b[20~",	"\x1b[20~"	}, 	    	// KeyF9
{ 0,		0		},              // KeyF10
{ 0,		0		},              // KeyF11
{ 0,		0		},              // KeyF12
{ 0,		0		},              // KeyApplication
{ 0,		0		},              // KeyCapsLock
{ 0,		0		},              // KeyPrintScreen
{ 0,		0		},              // KeyScrollLock
{ 0,		0		},              // KeyPause
{ 0,		0		},              // KeyNumLock
{ "/",		"/"		},            	// KeyKP_Divide
{ "*",		"*"		},            	// KeyKP_Multiply
{ "-",		"-"		},            	// KeyKP_Subtract
{ "+",		"+"		},            	// KeyKP_Add
{ "\n",		"\n"		},           	// KeyKP_Enter
{ "1",		"1"		},            	// KeyKP_1
{ "2",		"2"		},            	// KeyKP_2
{ "3",		"3"		},            	// KeyKP_3
{ "4",		"4"		},            	// KeyKP_4
{ "5",		"5"		},            	// KeyKP_5
{ "6",		"6"		},            	// KeyKP_6
{ "7",		"7"		},            	// KeyKP_7
{ "8",  	"8"		},	        // KeyKP_8
{ "9",		"9"		},            	// KeyKP_9
{ "0",		"0"		},            	// KeyKP_0
{ "\x1b[G",	"\x1b[G"	},       	// KeyKP_Center
{ ",",		","		},            	// KeyKP_Comma
{ ".",		"."		}             	// KeyKP_Period
